POST http://localhost:5500/api/v1/files/write 
Content-Type: application/json

{
    "id": "2313121232kada",
    "fileName": "sdsdd",
    "url": "https://file.com",
    "type": "sdsd",
    "size": 233,
    "folderId": "9f9e7169-acba-4d3b-91d2-de037f77b1f9",
    "metadata": {},
    "isStarred": false,
    "comments": {"content": "dsdsdsdsd", "name":"dsd"},
    "md5Hash": "30830123010290190291021292847128",
    "isShared": false,
    "shareToken": "rrwewe"
}